version: 2
jobs:
  build:
    branches:
      only:
        - development
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: npm run cover
